use project;

CREATE TABLE User(
	UserID INT NOT NULL AUTO_INCREMENT,
	email VARCHAR(255) UNIQUE NOT NULL,
    address VARCHAR(255) NULL,
    phoneNo VARCHAR(8) NOT NULL,
    password VARCHAR(255) NOT NULL,
    PRIMARY KEY (UserID)
);
DESCRIBE User;

-- NOT READY
CREATE TABLE Bookmark(
	BookmarkID INT NOT NULL AUTO_INCREMENT,
	description VARCHAR(255) NULL,
    UserID INT NOT NULL,
    PMI_ID INT NULL,
    FD_ID INT NULL,
    PRIMARY KEY (BookmarkID),
    FOREIGN KEY (UserID) REFERENCES User(UserID) 
    ON UPDATE CASCADE ON DELETE CASCADE,
	FOREIGN KEY (PMI_ID) REFERENCES pmidetails(PMI_ID) 
    ON UPDATE CASCADE ON DELETE CASCADE,
	FOREIGN KEY (FD_ID) REFERENCES flatdetails(FD_ID) 
    ON UPDATE CASCADE ON DELETE CASCADE    
);
DESCRIBE Bookmark;