-- use project DB
use project;

/*Insert Region*/
INSERT INTO Region
VALUES ('1', 'ANG MO KIO');

INSERT INTO Region
VALUES ('2', 'BEDOK');

INSERT INTO Region
VALUES ('3', 'BISHAN');

INSERT INTO Region
VALUES ('4', 'BUKIT BATOK');

INSERT INTO Region
VALUES ('5', 'BUKIT MERAH');

INSERT INTO Region
VALUES ('6', 'BUKIT PANJANG');

INSERT INTO Region
VALUES ('7', 'BUKIT TIMAH');

INSERT INTO Region
VALUES ('8', 'CENTRAL AREA');

INSERT INTO Region
VALUES ('9', 'CHOA CHU KANG');

INSERT INTO Region
VALUES ('10', 'CLEMENTI');

INSERT INTO Region
VALUES ('11', 'GEYLANG');

INSERT INTO Region
VALUES ('12', 'HOUGANG');

INSERT INTO Region
VALUES ('13', 'JURONG EAST');

INSERT INTO Region
VALUES ('14', 'JURONG WEST');

INSERT INTO Region
VALUES ('15', 'KALLANG/WHAMPOA');

INSERT INTO Region
VALUES ('16', 'MARINE PARADE');

INSERT INTO Region
VALUES ('17', 'PASIR RIS');

INSERT INTO Region
VALUES ('18', 'PUNGGOL');

INSERT INTO Region
VALUES ('19', 'QUEENSTOWN');

INSERT INTO Region
VALUES ('20', 'SEMBAWANG');

INSERT INTO Region
VALUES ('21', 'SENGKANG');

INSERT INTO Region
VALUES ('22', 'SERANGOON');

INSERT INTO Region
VALUES ('23', 'TAMPINES');

INSERT INTO Region
VALUES ('24', 'TOA PAYOH');

INSERT INTO Region
VALUES ('25', 'WOODLANDS');

INSERT INTO Region
VALUES ('26', 'YISHUN');

-- 26 lines
describe region