use project;

CREATE TABLE PropertyType(
	PType_ID INT NOT NULL AUTO_INCREMENT,
    propertyType VARCHAR(100) NOT NULL,
    PRIMARY KEY (PType_ID)
);
DESCRIBE PropertyType;

CREATE TABLE PMIDetails(
	PMI_ID INT NOT NULL AUTO_INCREMENT,
    project VARCHAR(255) NOT NULL,
    street VARCHAR(255) NOT NULL,
    typeOfArea VARCHAR(50) NULL,
    tenure VARCHAR(50) NULL,
    PType_ID INT NOT NULL,
	PRIMARY KEY (PMI_ID),
    FOREIGN KEY (PType_ID) REFERENCES propertytype(PType_ID)
    ON UPDATE CASCADE ON DELETE CASCADE 
);
DESCRIBE PMIDetails;

CREATE TABLE PMISale(
	PSALE_ID INT NOT NULL AUTO_INCREMENT,
    area float NOT NULL,
    price float NOT NULL,
    PMI_ID INT NOT NULL,
    QuarterID INT NOT NULL,
	PRIMARY KEY (PSALE_ID),
    FOREIGN KEY (PMI_ID) REFERENCES pmidetails(PMI_ID)
    ON UPDATE CASCADE ON DELETE CASCADE,
	FOREIGN KEY (QuarterID) REFERENCES quarter(QuarterID)
    ON UPDATE CASCADE ON DELETE CASCADE 
);
DESCRIBE PMISale;

CREATE TABLE PMIRent(
	PRENT_ID INT NOT NULL AUTO_INCREMENT,
    areaRange VARCHAR(100) NOT NULL,
    rent_price float NOT NULL,
    PMI_ID INT NOT NULL,
    QuarterID INT NOT NULL,
	PRIMARY KEY (PRENT_ID),
    FOREIGN KEY (PMI_ID) REFERENCES pmidetails(PMI_ID)
    ON UPDATE CASCADE ON DELETE CASCADE,
	FOREIGN KEY (QuarterID) REFERENCES quarter(QuarterID)
    ON UPDATE CASCADE ON DELETE CASCADE 
);
DESCRIBE PMIRent;

